
# LINTER OPTIONS
# --------------
options:
    # Don't merge default rules
    merge-default-rules: false
    # formatter: compact
    formatter: stylish
    # Output file instead of logging results
    # output-file: 'sass-lint.html'

# FILE OPTIONS
# ------------
files:
    include: 'css/**/*.scss'
    ignore:
        # - 'scss/vendor/**/*.*'
        # # - 'scss/modules/**/*.*'
        # - 'scss/modules/*mixin*.*'
        # - 'scss/modules/*function*.*'
        - 'css/scss/modules/functions/*.*'
        - 'css/scss/partials/_normalize.scss'

# RULE CONFIGURATION
# ------------------
rules:
    # Extends
    extends-before-mixins: 1
    extends-before-declarations: 1
    placeholder-in-extend: 1

    # Mixins
    mixins-before-declarations:
        - 1
        -
            exclude:
                - breakpoint
                - exports
                - manual-font-resizer
                - responsive-video
                - form-styles
                - footer-logo
                - rem
                - change-captcha-size
                - replace-text-with-dimensions

    # Line Spacing
    one-declaration-per-line: 1
    empty-line-between-blocks: 1
    single-line-per-selector: 1

    # Disallows
    no-color-keywords: 1
    no-color-literals: 0
    no-css-comments: 0
    no-debug: 0
    no-duplicate-properties:
        - 1
        -
            exclude:
                - display
    no-empty-rulesets: 1
    no-extends: 0
    no-ids: 0
    no-important: 0
    no-invalid-hex: 1
    no-mergeable-selectors: 0
    no-misspelled-properties: 1
    # no-qualifying-elements:
    #         - 1
    #         -
    #             allow-element-with-attribute: true
    no-qualifying-elements: 0
    no-trailing-zero: 1
    no-transition-all: 1
    no-url-protocols: 1
    no-vendor-prefixes:
        - 1
        -
            excluded-identifiers:
                - webkit
    no-warn: 0
    property-units: 0

    # Nesting
    # force-attribute-nesting: 1
    # force-element-nesting: 1
    force-attribute-nesting: 0
    force-element-nesting: 0
    force-pseudo-nesting: 0

    # Name Formats
    class-name-format: 0
    function-name-format: 1
    id-name-format: 0
    mixin-name-format: 1
    placeholder-name-format: 1
    variable-name-format: 0

    # Style Guide
    bem-depth: 0
    border-zero: 1
    brace-style:
        - 1
        -
            allow-single-line: false
    clean-import-paths: 1
    empty-args: 1
    hex-length:
        - 1
        -
            style: long
    hex-notation: 1
    indentation:
        - 1
        -
            size: 4
    leading-zero:
        - 1
        -
            include: true
    nesting-depth:
        - 1
        -
            max-depth: 4
    property-sort-order:
        - 1
        -
            order:
                # POSITIONING
                - 'position'
                - 'z-index'
                - 'top'
                - 'right'
                - 'bottom'
                - 'left'
                # VISIBILITY
                - 'visibility'
                - 'opacity'
                # DISPLAY & BOX MODEL
                - 'clear'
                - 'float'
                - 'box-sizing'
                - 'overflow'
                - 'overflow-x'
                - 'overflow-y'
                - 'display'
                # -
                - 'width'
                - 'min-width'
                - 'max-width'
                # -
                - 'height'
                - 'min-height'
                - 'max-height'
                # -
                - 'padding'
                - 'padding-top'
                - 'padding-right'
                - 'padding-bottom'
                - 'padding-left'
                # -
                - 'border'
                - 'border-top'
                - 'border-right'
                - 'border-bottom'
                - 'border-left'
                # -
                - 'border-width'
                - 'border-top-width'
                - 'border-right-width'
                - 'border-bottom-width'
                - 'border-left-width'
                # -
                - 'border-style'
                - 'border-top-style'
                - 'border-right-style'
                - 'border-bottom-style'
                - 'border-left-style'
                # -
                - 'border-color'
                - 'border-top-color'
                - 'border-right-color'
                - 'border-bottom-color'
                - 'border-left-color'
                # -
                - 'border-radius'
                - 'border-top-left-radius'
                - 'border-top-right-radius'
                - 'border-bottom-left-radius'
                - 'border-bottom-right-radius'
                # -
                - 'margin'
                - 'margin-top'
                - 'margin-right'
                - 'margin-bottom'
                - 'margin-left'
                # -
                - 'outline'
                - 'outline-color'
                - 'outline-offset'
                - 'outline-style'
                - 'outline-width'
                # OHTER
                - 'background'
                - 'background-color'
                - 'background-image'
                - 'background-repeat'
                - 'background-position'
                - 'background-size'
                - 'background-origin'
                - 'background-clip'
                - 'background-attachment'
                - 'color'
                # -
                - 'font'
                - 'font-family'
                - 'font-size'
                - 'font-weight'
                - 'font-stretch'
                - 'font-style'
                - 'font-variant'
                - 'font-size-adjust'
                - 'font-smoothing'
                # -
                - 'text-align'
                - 'text-align-last'
                - 'text-indent'
                - 'text-transform'
                - 'text-decoration'
                - 'text-rendering'
                - 'text-shadow'
                - 'text-overflow'
                - 'vertical-align'
                - 'line-height'
                - 'letter-spacing'
                - 'word-spacing'
                - 'white-space'
                # -
                - 'list-style'
                - 'list-style-image'
                - 'list-style-position'
                - 'list-style-type'
                # -
                - 'cursor'
                - 'box-shadow'
                # -
                - 'columns'
                - 'column-gap'
                - 'column-fill'
                - 'column-rule'
                - 'column-span'
                - 'column-count'
                - 'column-width'
                # -
                - 'transform'
                - 'transform-origin'
                - 'transform-style'
                - 'transition'
                - 'transition-delay'
                - 'transition-duration'
                - 'transition-property'
                - 'transition-timing-function'
                # -
                - 'animation'
                - 'animation-name'
                - 'animation-duration'
                - 'animation-timing-function'
                - 'animation-delay'
                - 'animation-iteration-count'
                - 'animation-direction'
                - 'animation-fill-mode'
                - 'animation-play-state'
                # -
                - 'caption-side'
                - 'table-layout'
                - 'border-collapse'
                - 'border-spacing'
                - 'empty-cells'
                - 'content'
                - 'quotes'
            ignore-custom-properties: true
    quotes: 1
    shorthand-values: 1
    url-quotes: 1
    variable-for-property: 0
    zero-unit: 1

    # Inner Spacing
    space-after-comma: 1
    space-before-colon: 1
    space-after-colon: 1
    space-before-brace: 1
    space-before-bang: 1
    space-after-bang: 1
    space-between-parens: 1
    space-around-operator: 1

    # Final Items
    trailing-semicolon: 1
    final-newline: 1