<?php include('libs/functions'); ?>
<!DOCTYPE html>
<!--[if lt IE 7]>			 <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>				 <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>				 <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title>Pernod Ricard México::.</title>
		<meta name="description" content="Pernod Ricard México">
		<meta name="viewport" content="width=device-width">
		<link rel="shortcut icon" type="image/x-icon" href="/imgs/design/favicon.ico">
		<link rel="stylesheet" href="/css/style.css">
		<link rel="stylesheet" href="/css/jquery.fancybox.css?v=2.1.5">
		<script src="/js/modernizr-2.6.2.min.js"></script>
		<?php include('libs/jquery-1.11.0'); ?>
		<!--[if lt IE 9]>
			<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
	<body class="contColor">
		<?php include('libs/header'); ?>
		<div id="container" class="generalBack">
			<div class="panel">
				<div class="content APrivacidad clearfix">
					<header class="sectionHeader">
						<h2 class="sectionTitle">AVISO DE PRIVACIDAD</h2>
					</header>
					<div class="APrivacidadPanel">
						<ul>
							<li><a href="#Clientes_INVIDO_131001" class="knwAP">Clientes INVIDO 131001</a></li>
							<li><a href="#Prest_Serv_INVIDO_131001" class="knwAP">Prestadores de Servicios INVIDO 131001</a></li>
							<li><a href="#Prest_Serv_PRM_Ingles" class="knwAP">Prestadores de Servicios PRM (Inglés)</a></li>
							<li><a href="#Prest_Serv_VPD_ima" class="knwAP">Prestadores de Servicios VPD ima</a></li>
							<li><a href="#Rep_Leg_INVIDO_YYN_130902" class="knwAP">Rep. Legales INVIDO YYN 130902</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div id="Clientes_INVIDO_131001" class="pUpAP-Frmt">
			<h2>AVISO DE PRIVACIDAD</h2>
			<p>En cumplimiento a lo previsto en la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (en lo sucesivo &quot;la Ley&quot;), nos permitimos informarle lo siguiente:</p>
			<h3>1.- RESPONSABLE DE LOS DATOS PERSONALES</h3>
			<p>Industrias Vinícolas Pedro Domecq S.A. de C.V., (en lo sucesivo &quot;INVIDO&quot;), señalando para efectos del presente Aviso de Privacidad el domicilio ubicado en Paseo de los Tamarindos 100, piso 3, Colonia Bosques de las Lomas, Delegación Cuajimalpa, México Distrito Federal, Código Postal 05120, será el responsable de los datos personales que le sean proporcionados por las personas físicas a quienes correspondan los mismos (en lo sucesivo el &ldquo;Titular&rdquo; o los &ldquo;Titulares&rdquo;).</p>
			<h3>2.- DATOS PERSONALES QUE SE SOLICITAN DEL TITULAR</h3>
			<p>Para las finalidades señaladas en el presente Aviso de Privacidad, <strong>INVIDO</strong> podrá recabar los datos personales del Titular interesado en contratar alguno de los servicios o en adquirir alguno de los productos de <strong>INVIDO</strong> como son: nombre (identificación oficial así como la imagen del Titular al ingresa a las instalaciones de <strong>INVIDO</strong> a través  de las cámaras de videovigilancia y seguridad), domicilio, teléfono fijo, teléfono celular, nacionalidad, fecha de nacimiento, estado civil, régimen conyugal, Registro Federal de Contribuyentes (RFC), Clave Única de Registro de Población (CURP) información patrimonial (relación de bienes y relación de ingresos), número de cuenta bancaria, y ocupación o actividad profesional.</p>
			<p>Por otra parte, para aquellas personas que tengan el carácter de Avales u Obligados Solidarios de un Titular interesado en contratar alguno de los servicios o en adquirir alguno de los productos de <strong>INVIDO </strong>se les informa que éste último únicamente requiere sus Datos Personales correspondientes a: nombre (identificación oficial así como la imagen del Titular al ingresar a las instalaciones de <strong>INVIDO</strong> a través  de las cámaras de videovigilancia y seguridad), domicilio, estado civil, régimen conyugal (copia del acta de matrimonio), Registro Federal de Contribuyentes (RFC) e información patrimonial (relación de bienes). Datos Personales de los que los Avales u Obligados Solidarios son Titulares en términos del presente Aviso de Privacidad.</p>
			<p>Para aquellas personas que tengan el carácter de Cónyuge de un Titular, se les informa que <strong>INVIDO</strong> únicamente requiere sus Datos Personales correspondientes a nombre (identificación oficial así como la imagen del Titular al ingresa a las instalaciones de <strong>INVIDO</strong> a través de las cámaras de videovigilancia y seguridad) y régimen conyugal (copia del acta de matrimonio), sin embargo, en caso de estar casado bajo el régimen de sociedad conyugal se requiere también información patrimonial (relación de bienes). Datos Personales de los que los Cónyuges son Titulares en términos del presente Aviso de Privacidad.</p>
			<p>Los Titulares interesados en contratar alguno de los servicios o en adquirir alguno de los productos de <strong>INVIDO</strong> que proporcionen a éste último los Datos Personales de los Titulares con carácter de Avales u Obligados Solidarios o de los Titulares con carácter de Cónyuges deberán notificarles haber proporcionado sus Datos Personales a <strong>INVIDO</strong> y el contenido del presente Aviso de Privacidad, lo anterior, con independencia de la notificación que <strong>INVIDO</strong> hará a dichos Titulares del Aviso de Privacidad al primer contacto que tenga con éstos últimos.</p>
			<p>Los Datos Personales de los Titulares se podrán recabar de las siguientes formas: i) cuando el Titular los proporcione personal o directamente, ii) cuando <strong>INVIDO</strong> los obtenga de forma indirecta, iii) cuando el Titular utilice el sitio de internet o los servicios en línea de <strong>INVIDO</strong> y/o iv) cuando se obtengan por <strong>INVIDO</strong> a través de las fuentes permitidas por la legislación.</p>
			<p>En términos de lo dispuesto por el artículo 14 del Reglamento de la Ley cuando <strong>INVIDO</strong> no haga del conocimiento de los Titulares el presente Aviso de Privacidad de manera directa o personal sino de forma indirecta, los Titulares cuentan con un plazo de 5 (cinco) días hábiles a partir de que les fue puesto a disposición el Aviso de Privacidad para que de ser el caso manifiesten su oposición al tratamiento de sus Datos Personales que pretendan ser utilizados por <strong>INVIDO</strong> para finalidades no necesarias para cumplir una relación jurídica con éste último, oposición que deberán manifestar de acuerdo a lo dispuesto en la sección cinco (5) del presente Aviso de Privacidad, ya que, en caso de que los Titulares no manifieste su oposición se entenderá que otorgan su consentimiento a <strong>INVIDO</strong>.</p>
			<p>Es responsabilidad del Titular de los Datos Personales, el garantizar que los datos que facilite personal o directamente a <strong>INVIDO</strong> sean veraces y completos, así como de notificar a <strong>INVIDO</strong> cualquier modificación a los mismos para dar cumplimiento a la obligación de mantener la información actualizada.</p>
			<h3>3.- FINALIDADES PARA LAS QUE SE RECABAN LOS DATOS PERSONALES</h3>
			<p>La información de Datos Personales, que es recolectada por <strong>INVIDO</strong> del Titular interesado en contratar alguno de los servicios o en adquirir alguno de los productos de <strong>INVIDO</strong> tendrá el uso que se describe a continuación: <strong>i)</strong> para la relación correspondiente a la prestación de los servicios y/o la venta de los productos ofrecidos por <strong>INVIDO </strong>(en adelante y en su conjunto los Servicios), <strong>ii)</strong> para el cumplimiento de los contratos que celebre <strong>INVIDO</strong> con el Titular, <strong>iii)</strong> para la identificación del Titular, <strong>iv)</strong> para la administración de los Servicios, <strong>v)</strong> para el análisis de los Servicios, <strong>vi)</strong> para la actualización de datos del Titular, <strong>vii)</strong> para el análisis de las solicitudes de crédito del Titular que pretenda contratar Servicios de <strong>INVIDO</strong> y <strong>viii) </strong>proporcionar seguridad a las instalaciones de <strong>INVIDO</strong> y a los Titulares que ingresen a éstas últimas, finalidades que son necesarias para cumplir las obligaciones derivadas de la relación jurídica que tenga <strong>INVIDO</strong> con el Titular.</p>
			<p>Asimismo, dentro del uso que <strong>INVIDO</strong> dará a la información del Titular interesado en contratar alguno de los servicios o en adquirir alguno de los productos de <strong>INVIDO</strong> está: <strong>i)</strong> el ofrecimiento y promoción de bienes, productos y servicios y/o prospección comercial así como <strong>ii)</strong> evaluar la calidad de los Servicios, finalidades que no necesariamente se requieren para cumplir con las obligaciones derivadas de la relación jurídica que tenga <strong>INVIDO</strong> con el Titular, por lo que, en caso de que el Titular no esté de acuerdo en que <strong>INVIDO</strong> utilice sus Datos Personales para dichas finalidades deberá manifestar su oposición de acuerdo a lo dispuesto en la sección cinco (5) del presente Aviso de Privacidad, ya que, en caso de que el Titular no manifieste su oposición se entenderá que otorga su consentimiento a <strong>INVIDO</strong>.</p>
			<p>En relación a los Datos Personales que recaba <strong>INVIDO</strong> de aquellos Titulares que tienen el carácter de Avales u Obligados Solidarios de los Titulares interesado en contratar alguno de los servicios o en adquirir alguno de los productos de <strong>INVIDO</strong> se les informa que las finalidades para las que este último utiliza sus Datos Personales son únicamente las contenidas en los puntos (i) a (viii) del primer párrafo de la presente sección finalidades que son necesarias para cumplir las obligaciones derivadas de la relación jurídica que tenga <strong>INVIDO</strong> con dichos Titulares derivadas de su designación como Avales u Obligados Solidarios.</p>
			<p>Con respecto a los Datos Personales de aquellos Titulares que tengan el carácter de Cónyuges de algún otro Titular se les informa que las finalidades para las que este último utiliza sus Datos Personales son: <strong>i)</strong> en caso de estar casados bajo el régimen de separación de bienes las contenidas en los puntos (iii), (vi), (vii) y (viii) del primer párrafo de la presente sección finalidades que no son necesarias para cumplir las obligaciones derivadas de la relación jurídica que tenga <strong>INVIDO</strong> con dichos Titulares, por lo que, en caso de que el Titular no esté de acuerdo en que <strong>INVIDO</strong> utilice sus Datos Personales para dichas finalidades deberá manifestar su oposición de acuerdo a lo dispuesto en la sección cinco (5) del presente Aviso de Privacidad, ya que, en caso de que el Titular no manifieste su oposición se entenderá que otorga su consentimiento a <strong>INVIDO</strong> y <strong>ii)</strong> en caso de estar casado bajo el régimen de sociedad conyugal las contenidas en los puntos (i) a (viii) del primer párrafo de la presente sección finalidades que son necesarias para cumplir las obligaciones derivadas de la relación jurídica que tenga <strong>INVIDO</strong> con dichos Titulares.</p>
			<p>En relación a los Datos Personales de aquellos Titulares que en el pasado otorgaron sus datos a <strong>INVIDO</strong> y que actualmente ya no tienen una relación con éste último así como de los Avales, Obligados Solidarios y Cónyuges de dichos Titulares, se les informa que <strong>INVIDO</strong> únicamente conserva sus Datos Personales de conformidad a lo dispuesto por el artículo 25 de la Ley, es decir, durante el periodo de bloqueo<span class="sprRmn">1</span> establecido en dicho ordenamiento legal, por lo que, una vez transcurrido dicho periodo de bloqueo sus Datos Personales serán suprimidos.</p>
			<h3>4.- TEMPORALIDAD, REMISIONES Y TRANSFERENCIAS</h3>
			<p>La temporalidad del manejo de los Datos Personales de los Titulares, dependerá de la relación jurídica que se tenga celebrada con <strong>INVIDO</strong>, así como de las obligaciones exigidas por la legislación vigente las autoridades competentes y las políticas internas de <strong>INVIDO</strong>, sin embargo, en relación a los Datos Personales correspondientes a la imagen de los Titulares que es captada por las cámaras de videovigilancia, dicha información es conservada por <strong>INVIDO</strong> únicamente por un plazo de 30 (treinta) a 60 (sesenta) días hábiles posteriores a la fecha en la que se obtiene.</p>
			<p>La información que sea entregada a <strong>INVIDO</strong>, será  resguardada, conservada y protegida, por éste último de acuerdo a lo dispuesto por la legislación vigente y las políticas internas de <strong>INVIDO</strong> para efecto de mantener la confidencialidad de dicha información.</p>
			<p>De acuerdo a lo dispuesto por la Ley, <strong>INVIDO</strong> dará acceso a los Datos Personales de los Titulares (a través de remisiones) a aquellas personas que tengan el carácter de Encargados<span class="sprRmn">2</span> como pueden ser prestadores de servicios, socios de negocios o terceros, que tengan una relación jurídica con <strong>INVIDO</strong>, que derivado de dicha relación jurídica necesiten conocer la información y asuman el compromiso de mantenerla bajo un estricto orden de confidencialidad y seguridad reconociendo además conocer los términos y condiciones del presente Aviso de Privacidad y comprometiéndose a dar cumplimiento a los mismos.</p>
			<p>Por otra parte, <strong>INVIDO</strong> transmite los Datos Personales de los Titulares cuyas operaciones son a crédito (excepto los Datos Personales de los Cónyuges de dichos Titulares casados bajo el régimen de separación de bienes) al Buró de Crédito (Trans Union de México, S.A. S.I.C), para efecto de revisar el comportamiento crediticio de dichos Titulares o bien para reportar a los Titulares que incumplen con sus obligaciones de pago, transferencia que no requiere del consentimiento de los Titulares de acuerdo a lo dispuesto en el artículo 37 de dicho ordenamiento legal.</p>
			<p>En caso de que los Datos Personales resguardados sean requeridos por una autoridad de cualquier índole o deban ser entregados a ésta última de acuerdo a la legislación vigente, estos datos se pondrán a su disposición dentro del estricto cumplimiento a la Ley, transferencia que no requiere del consentimiento de los Titulares de acuerdo a lo dispuesto en el artículo 37 de dicho ordenamiento legal.</p>
			<h3>5.- DERECHOS DE ACCESO, RECTIFICACIÓN, CANCELACIÓN, OPOSICIÓN, REVOCACIÓN Y LIMITACIÓN DE LOS DATOS PERSONALES.</h3>
			<p>Los Titulares de la información tendrán derecho a solicitar el acceso, rectificación, revocación, cancelación u oposición así como limitar el uso o divulgación de sus datos, mediante:</p>
			<p>a.- Solicitud escrita dirigida a la Vicepresidencia Jurídica y de Asuntos Corporativos de Industrias Vinícolas Pedro Domecq S.A. de C.V., al siguiente domicilio: Paseo de los Tamarindos 100, piso 3, Colonia Bosques de las Lomas, Delegación Cuajimalpa, México Distrito Federal, Código Postal 05120, de las 10:00 a las 17:00 horas, en días hábiles, o</p>
			<p>b.- Solicitud formulada al correo electrónico <a href="mailto:mxdatospersonales@pernod-ricard.com" class="lnk">mxdatospersonales@pernod-ricard.com</a></p>
			<p><strong>INVIDO</strong>, dará respuesta a las solicitudes del Titular de la información, siempre y cuando no se actualice alguna de las excepciones contenidas en la Ley, y el solicitante cumpla con lo dispuesto en el artículo 29 de dicho ordenamiento legal que establece los requisitos que debe contener las solicitudes presentadas por los Titulares.</p>
			<p>Para que <strong>INVIDO</strong> de trámite a la solicitud de un Titular referente al acceso, rectificación, revocación, cancelación, oposición y/o limitación del uso o divulgación de sus datos, éste último deberá adjuntar a su solicitud la siguiente información y documentación:</p>
			<ul class="lwr-Ltn">
				<li>Nombre del Titular y domicilio u otro medio para que <strong>INVIDO</strong> le comunique la respuesta a su solicitud.</li>
				<li>Los documentos con los que acredite su identidad o su personalidad en caso de la representación legal del Titular (identificación oficial del titular o del representante legal y poder de éste último). </li>
				<li>La descripción clara y precisa de los Datos Personales respecto de los que se busca ejercer el derecho de acceso, rectificación, revocación, cancelación, oposición, limitación del uso o divulgación, así como cualquier otro dato o documento que pueda facilitar la localización de los Datos Personales. </li>
			</ul>
			<p><strong>INVIDO</strong> dará respuesta a la solicitud de un Titular referente al acceso, rectificación, revocación, cancelación, oposición y/o limitación del uso o divulgación de sus datos dentro de los plazos establecidos en la Ley, es decir, dentro de los veinte (20) días siguientes contados a partir de que reciba la solicitud del Titular y en caso de que la solicitud sea procedente la misma se implementará dentro de los 15 (quince) días siguientes a que se le comunique al Titular la respuesta, plazos que podrán ser ampliados por <strong>INVIDO</strong> de acuerdo a lo dispuesto por el artículo 32 de la Ley.</p>
			<p>La obligación de acceso a la información se dará por cumplida por <strong>INVIDO</strong> cuando, en caso de que sea solicitado por el Titular, se ponga a disposición de éste último sus Datos Personales en copia simple en el domicilio de <strong>INVIDO</strong> durante el plazo de 15 (quince) días hábiles siguientes a que se le comunique al Titular la respuesta a su solicitud o bien a través de alguna de las formas establecidas en el artículo 33 de la Ley, mismas que en la respuesta a su solicitud se le notificarán al Titular.</p>
			<h3>6.- MODIFICACIONES AL AVISO DE PRIVACIDAD</h3>
			<p>En el supuesto, de que <strong>INVIDO</strong>, requiera usar sus Datos Personales con fines distintos a los pactados o convenidos al tenor de la relación jurídica que se tiene con el Titular y/o en el presente Aviso de Privacidad o bien requiera del Titular Datos Personales distintos a los señalados en el presente Aviso de Privacidad o pretenda realizar transferencias de los Datos Personales distintas a las señaladas en el presente Aviso de Privacidad, se notificará al Titular en forma escrita, telefónica, electrónica, o por cualquier medio óptico, sonoro, visual u otro que la tecnología permita ahora o en lo futuro explicando los nuevos usos que pretenda darle a dicha información a fin de obtener su consentimiento en términos de la Ley. Con el presente Aviso de Privacidad, los Titulares de la información quedan debidamente informados de los datos que se recabaron de ellos y con qué fines así como del hecho de que el Aviso de Privacidad podrá en todo momento ser consultado en la página de internet de <strong>INVIDO</strong> <a href="http://www.pernod-ricard-mexico.com" class="lnk">www.pernod-ricard-mexico.com</a>.</p>
			<p><strong>INVIDO</strong>, se reserva el derecho a modificar el presente Aviso de Privacidad para adaptarlo a novedades legislativas o jurisprudenciales así como a prácticas comerciales. En dichos supuestos, se anunciará en la página de internet <a href="http://www.pernod-ricard-mexico.com" class="lnk">www.pernod-ricard-mexico.com</a> los cambios de referencia.</p>
			<p>El presente Aviso de Privacidad, así como el manejo en general de la Ley que haga <strong>INVIDO</strong>, se rige por la legislación vigente y aplicable en los Estados Unidos Mexicanos, cualquier controversia que se suscite con motivo de su aplicación deberá ventilarse ante el Instituto Federal de Acceso a la Información y Protección de Datos (IFAI) o ante los Órganos Jurisdiccionales competentes en la Ciudad de México, Distrito Federal.</p>
			<p>Última actualización 1 de octubre de 2013.</p>
			<p>Consiento y autorizo que mis Datos Personales sean tratados conforme los términos y condiciones del presente Aviso de Privacidad.</p>
			<hr>
			<small><span class="sprRmn">1</span>Artículo 3 Fracción  III de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares establece que el Bloqueo es: La identificación y conservación de datos personales una vez cumplida la finalidad para  la cual fueron recabados, con el único propósito de determinar posibles responsabilidades en  relación con su tratamiento, hasta el plazo de prescripción legal o contractual de éstas. Durante  dicho periodo, los datos personales no podrán ser objeto de tratamiento y transcurrido éste, se  procederá a su cancelación en la base de datos que corresponde.</small><br>
			<small><span class="sprRmn">2</span>El artículo 3 de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares establece que el Encargado es la persona física o jurídica que sola o conjuntamente con otras trate datos personales por cuenta del Responsable.</small>
		</div>
		<div id="Prest_Serv_INVIDO_131001" class="pUpAP-Frmt">
			<h2>AVISO DE PRIVACIDAD</h2>
			<p>En cumplimiento a lo previsto en la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (en lo sucesivo &quot;la Ley&quot;), nos permitimos informarle lo siguiente:</p>
			<h3>1.- RESPONSABLE DE LOS DATOS PERSONALES</h3>
			<p>Industrias Vinícolas Pedro Domecq S.A. de C.V., (en lo sucesivo &quot;INVIDO&quot;), señalando para efectos del presente Aviso de Privacidad el domicilio ubicado en Paseo de los Tamarindos 100, piso 3, Colonia Bosques de las Lomas, Delegación Cuajimalpa, México Distrito Federal, Código Postal 05120, será el responsable de los datos personales que le sean proporcionados por las personas físicas a quienes correspondan los mismos (en lo sucesivo el &ldquo;Titular&rdquo;). </p>
			<h3>2.- DATOS PERSONALES QUE SE SOLICITAN DEL TITULAR</h3>
			<p>Para las finalidades señaladas en el presente Aviso de Privacidad, <strong>INVIDO</strong> podrá recabar los datos personales del Titular como son: nombre (identificación oficial así como la imagen del Titular al ingresar a las instalaciones de <strong>INVIDO</strong> a través  de las cámaras de videovigilancia y seguridad), domicilio, teléfono fijo, Registro Federal de Contribuyentes (RFC),  número de cuenta bancaria, y ocupación o actividad profesional (en adelante y en su conjunto los Datos Personales) de alguna de las siguientes formas: i) cuando el Titular los proporcione personal o directamente, ii) cuando <strong>INVIDO</strong> los obtenga de forma indirecta, iii) cuando el Titular utilice el sitio de internet o los servicios en línea de <strong>INVIDO</strong> y/o iv) cuando se obtengan por <strong>INVIDO</strong> a través de las fuentes permitidas por la legislación.</p>
			<p>En términos de lo dispuesto por el artículo 14 del Reglamento de la Ley cuando <strong>INVIDO</strong> no haga del conocimiento de los Titulares el presente Aviso de Privacidad de manera directa o personal sino de forma indirecta, los Titulares cuentan con un plazo de 5 (cinco) días hábiles a partir de que les fue puesto a disposición el Aviso de Privacidad para que de ser el caso manifiesten su oposición al tratamiento de sus Datos Personales que pretendan ser utilizados por <strong>INVIDO</strong> para finalidades no necesarias para cumplir una relación jurídica con éste último, oposición que deberán manifestar de acuerdo a lo dispuesto en la sección cinco (5) del presente Aviso de Privacidad, ya que, en caso de que los Titulares no manifieste su oposición se entenderá que otorgan su consentimiento a <strong>INVIDO</strong>. </p>
			<p>Es responsabilidad del Titular de los Datos Personales, el garantizar que los datos que facilite personal o directamente a <strong>INVIDO</strong> sean veraces y completos, así como de notificar a <strong>INVIDO</strong> cualquier modificación a los mismos para dar cumplimiento a la obligación de mantener la información actualizada.</p>
			<h3>3.- FINALIDADES PARA LAS QUE SE RECABAN LOS DATOS PERSONALES</h3>
			<p>La información de Datos Personales, que es recolectada por <strong>INVIDO</strong> del Titular tendrá el uso que se describe a continuación: <strong>i)</strong> para el cumplimiento de los contratos que celebre <strong>INVIDO</strong> con el Titular (en adelante los Contratos), <strong>ii)</strong> para la identificación del Titular, <strong>iii)</strong> para la administración de los Contratos, <strong>iv)</strong> para la actualización de datos del Titular, <strong>v)</strong> proporcionar seguridad a las instalaciones de <strong>INVIDO</strong> y a los Titulares que ingresen a éstas últimas, finalidades que son necesarias para cumplir las obligaciones derivadas de la relación jurídica que tenga <strong>INVIDO</strong> con el Titular.</p>
			<p>En relación a los Datos Personales de aquellos Titulares que en el pasado otorgaron sus datos a <strong>INVIDO</strong> y que actualmente ya no tienen una relación jurídica con éste último, se les informa a dichos Titulares que <strong>INVIDO</strong> únicamente conserva sus Datos Personales de conformidad a lo dispuesto por el artículo 25 de la Ley, es decir, durante el periodo de bloqueo<span class="sprRmn">1</span> establecido en dicho ordenamiento legal, por lo que, una vez transcurrido dicho periodo de bloqueo sus Datos Personales serán suprimidos.</p>
			<h3>4.- TEMPORALIDAD, REMISIONES Y TRANSFERENCIAS</h3>
			<p>La temporalidad del manejo de los Datos Personales del Titular, dependerá de la relación jurídica que se tenga celebrada con <strong>INVIDO</strong>, así como de las obligaciones exigidas por la legislación vigente las autoridades competentes y las políticas internas de <strong>INVIDO</strong>, sin embargo, en relación a los Datos Personales correspondientes a la imagen del Titular que es captada por las cámaras de videovigilancia, dicha información es conservada por <strong>INVIDO</strong> únicamente por un plazo de 30 (treinta) a 60 (sesenta) días hábiles posteriores a la fecha en la que se obtiene. </p>
			<p>La información que sea entregada a <strong>INVIDO</strong>, será  resguardada, conservada y protegida, por éste último de acuerdo a lo dispuesto por la legislación vigente y las políticas internas de <strong>INVIDO</strong> para efecto de mantener la confidencialidad de dicha información. </p>
			<p> De acuerdo a lo dispuesto por la Ley, <strong>INVIDO</strong> dará acceso a los Datos Personales del Titular (a través de remisiones) a aquellas personas que tengan el carácter de Encargados<span class="sprRmn">2</span> como pueden ser prestadores de servicios, socios de negocios o terceros, que tengan una relación jurídica con <strong>INVIDO</strong>, que derivado de dicha relación jurídica necesiten conocer la información y asuman el compromiso de mantenerla bajo un estricto orden de confidencialidad y seguridad reconociendo además conocer los términos y condiciones del presente Aviso de Privacidad y comprometiéndose a dar cumplimiento a los mismos.</p>
			<p>Por otra parte, <strong>INVIDO</strong> transmite los Datos Personales de los Titulares a las empresas filiales y/o subsidiarias de <strong>INVIDO </strong>con la finalidad de cumplir con las relaciones jurídicas que existen entre dichas empresas transferencias que no requieren del consentimiento del Titular de acuerdo a lo dispuesto en el artículo 37 de la LFPDP.</p>
			<p>En caso de que los Datos Personales resguardados sean requeridos por una autoridad de cualquier índole o deban ser entregados a ésta última de acuerdo a la legislación vigente, estos datos se pondrán a su disposición dentro del estricto cumplimiento a la Ley, transferencia que no requiere del consentimiento del Titular de acuerdo a lo dispuesto en el artículo 37 de dicho ordenamiento legal.</p>
			<h3>5.- DERECHOS DE ACCESO, RECTIFICACIÓN, CANCELACIÓN, OPOSICIÓN, REVOCACIÓN Y LIMITACIÓN DE LOS DATOS PERSONALES.</h3>
			<p>Los Titulares de la información tendrán derecho a solicitar el acceso, rectificación, revocación, cancelación u oposición así como limitar el uso o divulgación de sus datos, mediante:</p>
			<p>a.- Solicitud escrita dirigida a la Vicepresidencia Jurídica y de Asuntos Corporativos de Industrias Vinícolas Pedro Domecq S.A. de C.V., al siguiente domicilio: Paseo de los Tamarindos 100, piso 3, Colonia Bosques de las Lomas, Delegación Cuajimalpa, México Distrito Federal, Código Postal 05120, de las 10:00 a las 17:00 horas, en días hábiles, o</p>
			<p>b.- Solicitud formulada al correo electrónico <a href="mailto:mxdatospersonales@pernod-ricard.com" class="lnk">mxdatospersonales@pernod-ricard.com</a></p>
			<p><strong>INVIDO</strong>, dará respuesta a las solicitudes del Titular de la información, siempre y cuando no se actualice alguna de las excepciones contenidas en la Ley, y el solicitante cumpla con lo dispuesto en el artículo 29 de dicho ordenamiento legal que establece los requisitos que debe contener las solicitudes presentadas por los Titulares.</p>
			<p>Para que <strong>INVIDO</strong> de trámite a la solicitud de un Titular referente al acceso, rectificación, revocación, cancelación, oposición y/o limitación del uso o divulgación de sus datos, éste último deberá adjuntar a su solicitud la siguiente información y documentación:</p>
			<ul class="lwr-Ltn">
				<li>Nombre del Titular y domicilio u otro medio para que <strong>INVIDO</strong> le comunique la respuesta a su solicitud.</li>
				<li>Los documentos con los que acredite su identidad o su personalidad en caso de la representación legal del Titular (identificación oficial del titular o del representante legal y poder de éste último). </li>
				<li>La descripción clara y precisa de los Datos Personales respecto de los que se busca ejercer el derecho de acceso, rectificación, revocación, cancelación, oposición, limitación del uso o divulgación, así como cualquier otro dato o documento que pueda facilitar la localización de los Datos Personales. </li>
			</ul>
			<p><strong>INVIDO </strong>dará respuesta a la solicitud de un Titular referente al acceso, rectificación, revocación, cancelación, oposición y/o limitación del uso o divulgación de sus datos dentro de los plazos establecidos en la Ley, es decir, dentro de los veinte (20) días siguientes contados a partir de que reciba la solicitud del Titular y en caso de que la solicitud sea procedente la misma se implementará dentro de los 15 (quince) días siguientes a que se le comunique al Titular la respuesta, plazo que podrá ser ampliado por <strong>INVIDO</strong> de acuerdo a lo dispuesto por el artículo 32 de la Ley. </p>
			<p>La obligación de acceso a la información se dará por cumplida por <strong>INVIDO</strong> cuando, en caso de que sea solicitado por el Titular, se ponga a disposición de éste último sus Datos Personales en copia simple en el domicilio de <strong>INVIDO</strong> durante el plazo de 15 (quince) días hábiles siguientes a que se le comunique al Titular la respuesta a su solicitud o bien a través de alguna de las formas establecidas en el artículo 33 de la Ley, mismas que en la respuesta a su solicitud se le notificarán al Titular.</p>
			<h3>6.- MODIFICACIONES AL AVISO DE PRIVACIDAD</h3>
			<p>En el supuesto, de que <strong>INVIDO</strong>, requiera usar sus Datos Personales con fines distintos a los pactados o convenidos al tenor de la relación jurídica que se tiene con el Titular y en el presente Aviso de Privacidad o bien requiera del Titular Datos Personales distintos a los señalados en el presente Aviso de Privacidad o pretenda realizar transferencias de los Datos Personales distintas a las señaladas en el presente Aviso de Privacidad, se notificará al Titular en forma escrita, telefónica, electrónica, o por cualquier medio óptico, sonoro, visual u otro que la tecnología permita ahora o en lo futuro explicando los nuevos usos que pretenda darle a dicha información a fin de obtener su consentimiento en términos de la Ley. Con el presente Aviso de Privacidad, los Titulares de la información quedan debidamente informados de los datos que se recabaron de ellos y con qué fines así como del hecho de que el Aviso de Privacidad podrá en todo momento ser consultado en la página de internet de <strong>INVIDO</strong> <a href="http://www.pernod-ricard-mexico.com" class="lnk">www.pernod-ricard-mexico.com</a>. </p>
			<p><strong>INVIDO</strong>, se reserva el derecho a modificar el presente Aviso de Privacidad para adaptarlo a novedades legislativas o jurisprudenciales así como a prácticas comerciales. En dichos supuestos, se anunciará en la página de internet <a href="http://www.pernod-ricard-mexico.com" class="lnk">www.pernod-ricard-mexico.com</a> los cambios de referencia. </p>
			<p>El presente Aviso de Privacidad, así como el manejo en general de la Ley que haga <strong>INVIDO</strong>, se rige por la legislación vigente y aplicable en los Estados Unidos Mexicanos, cualquier controversia que se suscite con motivo de su aplicación deberá ventilarse ante el Instituto Federal de Acceso a la Información y Protección de Datos (IFAI) o ante los Órganos Jurisdiccionales competentes en la Ciudad de México, Distrito Federal.</p>
			<p>Última actualización 1 de octubre de 2013.</p>
			<p>Consiento y autorizo que mis Datos Personales sean tratados conforme los términos y condiciones del presente Aviso de Privacidad.</p>
			<hr>
			<small><span class="sprRmn">1</span> Artículo 3 Fracción  III de la Ley  Federal de Protección de Datos Personales en Posesión de los Particulares  establece que el Bloqueo es: La identificación y conservación de datos  personales una vez cumplida la finalidad para   la cual fueron recabados, con el único propósito de determinar posibles  responsabilidades en  relación con su  tratamiento, hasta el plazo de prescripción legal o contractual de éstas.  Durante  dicho periodo, los datos  personales no podrán ser objeto de tratamiento y transcurrido éste, se  procederá a su cancelación en la base de  datos que corresponde. </small><br>
			<small><span class="sprRmn">2</span>El  artículo 3 de la Ley Federal de Protección de Datos Personales en Posesión de  los Particulares establece que el Encargado es la persona física o jurídica que  sola o conjuntamente con otras trate datos personales por cuenta del  Responsable. </small>
		</div>
		<div id="Prest_Serv_PRM_Ingles" class="pUpAP-Frmt">
			<h2>PRIVACY NOTICE DISCLOSURE</h2>
			<p>Pursuant to what is set forth in the Ley Federal de Protección de Datos Personales en Posesión de los Particulares (hereinafter referred to as &ldquo;the Law &quot;), we would like to inform you the following:</p>
			<h3>1.- INDIVIDUAL OR ENTITY IN CHARGE OF THE PERSONAL DATA</h3>
			<p>Pernod Ricard México, S.A. de C.V., (hereinafter referred to as &quot;PRM&quot;), having as its address for the purposes of the present Privacy Notice Disclosure that located at Paseo de los Tamarindos 100, piso 3, Colonia Bosques de las Lomas, Delegación Cuajimalpa, México Distrito Federal, Código Postal 05120, will be the entity in charge of the personal data to be provided to the same by the relevant individuals (personas físicas, in Spanish) (hereinafter referred to as the &ldquo;Holder&rdquo; or &ldquo;Holder´s&rdquo;). </p>
			<h3>2.- PERSONAL DATA REQUIRED FROM THE HOLDER</h3>
			<p>For the purposes referred to in the present Privacy Notice Disclosure, <strong>PRM</strong> may collect the personal data from the Holder, such as its name (official ID, as well as the image from the Holder when entering into <strong>PRM</strong> facilities through security and video-surveillance cameras), address, landline phone, Federal Taxpayers&rsquo; Registry (RFC, in Spanish), bank account number and occupation or  professional activity (hereinafter and jointly referred to as &ldquo;Personal Data&rdquo;) in any of the following manners: i) when the Holder personally or directly provides them; ii) when <strong>PRM</strong> indirectly obtains them; iii) when the Holder uses <strong>PRM</strong>&rsquo;s website or online services; and/or iv) when such data are obtained by <strong>PRM</strong> through sources allowed by the legislation.</p>
			<p>The Personal Data Holder shall ensure that the data personally or directly provided to <strong>PRM</strong> by the former are full and accurate. The former shall also provide <strong>PRM</strong> with notice of any modifications of the same in order to comply with the obligation of keeping the information updated.</p>
			<h3>3.- REASONS TO COLLECT PERSONAL DATA</h3>
			<p>Information on Personal Data, which is collected by <strong>PRM</strong> from the Holder, shall be used as follows: <strong>i)</strong> to comply with the contracts entered into between <strong>PRM</strong> and the Holder (hereinafter referred to as &ldquo;the Contracts&rdquo;); <strong>ii)</strong> to identify the Holder; <strong>iii)</strong> to manage the Contracts; i<strong>v)</strong> to update the Holder&rsquo;s data; <strong>v)</strong> to provide security to <strong>PRM</strong>&lsquo;s facilities and to the Holders entering into the same. Such requirements are needed in order to comply with the obligations resulting from the legal relationship between <strong>PRM</strong> and the Holder.</p>
			<p>Regarding the Personal Data of those Holders which in the past had a relationship with <strong>PRM&rsquo;</strong>s but not anymore we inform to that Holders that <strong>PRM </strong>only retains their Personal Data in accordance with the provisions of Article 25 of the Law, during the lockout period<span class="sprRmn">1</span> established in the Law, so that, after such period your Personal Data will be deleted.</p>
			<h3>4.- TIMEFRAMES, REFERRALS, AND TRANSFERS</h3>
			<p>Timeframes to manage the Holder&rsquo;s Personal Data shall depend on the legal relationship between the former and <strong>PRM</strong>, as well as on the obligations required by the legislation in force, the relevant authorities, and <strong>PRM</strong>&rsquo;s internal policies. However, concerning the Personal Data related to the Holder&rsquo;s images that are captured using video-surveillance cameras, such information shall be kept by <strong>PRM</strong> only for a term of 30 (thirty) to 60 (sixty) business days following the date on which it has been obtained.</p>
			<p>The information delivered to <strong>PRM</strong> shall be kept and protected by the latter pursuant to what is set forth in the legislation in force and <strong>PRM</strong>&rsquo;s internal policies in order to keep such information as confidential in nature. </p>
			<p>Pursuant to what is established by the Law, <strong>PRM</strong> shall provide access to the Holder&rsquo;s Personal Data (by means of referrals) to those individuals acting as Data Controllers<span class="sprRmn">2</span>, such as <strong>PRM</strong>&rsquo;s business partners or service suppliers that have a legal relationship with the former and that, as a result of such a legal relationship, need to know the information and commit to keep the same strictly confidential and reserved, and who shall state they know the terms and conditions of the present Privacy Notice Disclosure and commit to comply with the same.</p>
			<p>On the other hand, <strong>PRM</strong> provides to its affiliates and subsidiaries the Personal Data from the Holders, in order to comply with the legal relationships that <strong>PRM</strong> has with such companies. Such transfers shall not require the consent from the Holder under article 37 of the Law. </p>
			<p>If the Personal Data under protection should be required by any authorities or if they should be delivered to the latter pursuant to the legislation in force, such data shall be available for the same pursuant to the Law and such a transfer shall not require the consent from the Holder under article 37 of such a legal framework.</p>
			<h3>5.- RIGHTS OF PERSONAL DATA ACCESS, CORRECTION, CANCELLATION, OPPOSITON, RENEWAL, AND LIMITATION.</h3>
			<p>Holders of information shall have the right to require the access, correction, revocation, cancellation, or opposition, as well as limitation of use or disclosure of their data, by means of:</p>
			<p>a.- A written application submitted to the Vice-presidency of Legal and Corporate Issues from Pernod Ricard México, S.A. de C.V., to the following address: Paseo de los Tamarindos 100, piso 3, Colonia Bosques de las Lomas, Delegación Cuajimalpa, México Distrito Federal, Código Postal 05120, from 10:00 to 17:00 hours, in business days; or</p>
			<p>b.- An application sent to the electronic mail <a href="mailto:mxdatospersonales@pernod-ricard.com" class="lnk">mxdatospersonales@pernod-ricard.com</a></p>
			<p><strong>PRM</strong> shall provide an answer to the applications from the information Holder, provided exceptions included in the Law do not apply and the applicant complies with what is set forth in article 29 of the legal framework establishing the requirements for the applications submitted by the Holders.</p>
			<p>In order for <strong>PRM</strong> to process the application form a Holder regarding access, correction, revocation, cancellation, opposition, and/or limitation of use or disclosure of its data, the latter shall attach the following information and documentation to its application:</p>
			<ul class="lwr-Ltn">
				<li>The name of the Holder, as well as its address and any other means in order for <strong>PRM</strong> to provide the answer to its application.</li>
				<li>The documents evidencing its identity or status of the Holder legal representatives (official ID of the Holder or legal representative and the power of attorney of the latter). </li>
				<li>An accurate and precise description of the Personal Data for which the right of access, correction, revocation, cancellation, opposition, limitation of use or disclosure is requested, as well as any other data or document that may help to locate the relevant Personal Data. </li>
			</ul>
			<p><strong>PRM </strong>shall provide an answer to the application of a Holder regarding the access, correction, revocation, cancellation, opposition, and/or limitation of use or disclosure of its data within the terms established by the Law, that is, within the twenty (20) days following the reception of the Holder&rsquo;s application. Such a term may be extended by <strong>PRM</strong> pursuant to what is set forth in article 32 of the Law. </p>
			<p>Obligation of information access shall be deemed as complied with by <strong>PRM</strong> if, in case of being requested by the Holder, its Personal Data are made available to the latter at <strong>PRM</strong>&rsquo;s address during the term of 15 (fifteen) business days following the date on which the Holder is provided with the answer to its application, or by means of any of the manners set forth in article 33 of the Law, which will be notified to the Holder in such an answer to its application.</p>
			<h3>6.- MODIFICATIONS TO THE PRIVACY NOTICE DISCLOSURE</h3>
			<p>In case <strong>PRM</strong> requires to use its Personal Data for purposes other than the ones agreed upon according to the legal relationship with the Holder and in the present Privacy Notice Disclosure, or if the same requires from the Holder Personal Data other than those stated in the present Privacy Notice Disclosure, the Holder shall be notified in writing, by phone, electronically, or by means of any other visual, audio, or optical means, or any other allowed by the technology currently or in the future, explaining the new uses that are pretended for such an information, in order to obtain its consent under the Law. With the present Privacy Notice Disclosure, the information Holders are duly informed about the data being collected from them and for what purposes, as well as about the fact that such a Privacy Notice Disclosure may be looked up at all times at <strong>PRM</strong>&rsquo;s website <a href="http://www.pernod-ricard-mexico.com" class="lnk">www.pernod-ricard-mexico.com</a></p>
			<p><strong>INVIDO</strong> reserves its right to modify this Privacy Notice Disclosure in order to adapt the same to the latest jurisprudences or legislative innovations, as well as to trade practices. In such cases, the relevant changes shall be posted in the website <a href="http://www.pernod-ricard-mexico.com" class="lnk">www.pernod-ricard-mexico.com</a></p>
			<p>This Privacy Notice Disclosure, as well as the general compliance with the Law by <strong>PRM</strong>, shall be ruled by the legislation in force and applicable in the Mexican United States. Any controversies resulting from such an application shall be settled by the Federal Institute for Information Access and Data Protection (IFAI, in Spanish) or before the relevant Courts from Mexico City, Federal District.</p>
			<p>Latest update: March 7th, 2013.</p>
			<p>I hereby agree and authorize that my Personal Data are handled pursuant to the terms and conditions of the present Privacy Notice Disclosure.</p>
			<p>_______________________________(Name and signature)</p>
			<hr>
			<small><span class="sprRmn">1</span>Article 3 of  the Ley Federal de Protección de Datos Personales en Posesión de los  Particulares establishes that the &ldquo;lockout period&rdquo; is: The period of time on  which the person who obtains the Personal Data of a Holder may keep such  Personal Data after the fulfillment of the purpose for which it was collected, with  the sole intention of identifying any kind of responsibilities related to the  Personal Data treatment. The lockout period corresponds to the legal  prescription term established in any applicable law for any kind of  responsibilities that may be a consequence of the Personal Data treatment. At  the end of this period the corresponding database shall be cancelled. </small><br>
			<small><span class="sprRmn">2</span>Article 3 of  the Ley Federal de Protección de Datos Personales en Posesión de los  Particulares establishes that the Data Controller is the individual or entity that  individually or jointly handles personal data on behalf of the Individual or  Entity in Charge of such data. </small>
		</div>
		<div id="Prest_Serv_VPD_ima" class="pUpAP-Frmt">
			<h2>AVISOO  DE PRIVACIDAD</h2>
			<p>En cumplimiento a lo previsto en la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (en lo sucesivo &quot;la Ley&quot;), nos permitimos informarle lo siguiente:</p>
			<h3>1.- RESPONSABLE DE LOS DATOS PERSONALES</h3>
			<p>Vinos Pedro Domecq S.A. de C.V., (en lo sucesivo &quot;VPD&quot;), señalando para efectos del presente Aviso de Privacidad el domicilio ubicado en Paseo de los Tamarindos 100, piso 3, Colonia Bosques de las Lomas, Delegación Cuajimalpa, México Distrito Federal, Código Postal 05120, será el responsable de los datos personales que le sean proporcionados por las personas físicas a quienes correspondan los mismos (en lo sucesivo el &ldquo;Titular&rdquo;). </p>
			<h3>2.- DATOS PERSONALES QUE SE SOLICITAN DEL TITULAR</h3>
			<p>Para las finalidades señaladas en el presente Aviso de Privacidad, <strong>VPD </strong>podrá recabar los datos personales del Titular como son: nombre (identificación oficial así como la imagen del Titular al ingresar a las instalaciones de <strong>VPD</strong> a través de las cámaras de videovigilancia y seguridad), domicilio, teléfono fijo, Registro Federal de Contribuyentes (RFC), número de cuenta bancaria, y ocupación o actividad profesional (en adelante y en su conjunto los Datos Personales) de alguna de las siguientes formas: i) cuando el Titular los proporcione personal o directamente, ii) cuando <strong>VPD</strong> los obtenga de forma indirecta, iii) cuando el Titular utilice el sitio de internet o los servicios en línea de <strong>VPD</strong> y/o iv) cuando se obtengan por <strong>VPD</strong> a través de las fuentes permitidas por la legislación.</p>
			<p>En términos de lo dispuesto por el artículo 14 del Reglamento de la Ley cuando <strong>VPD</strong> no haga del conocimiento de los Titulares el presente Aviso de Privacidad de manera directa o personal sino de forma indirecta, los Titulares cuentan con un plazo de 5 (cinco) días hábiles a partir de que les fue puesto a disposición el Aviso de Privacidad para que de ser el caso manifiesten su oposición al tratamiento de sus Datos Personales que pretendan ser utilizados por <strong>VPD</strong> para finalidades no necesarias para cumplir una relación jurídica con éste último, oposición que deberán manifestar de acuerdo a lo dispuesto en la sección cinco (5) del presente Aviso de Privacidad, ya que, en caso de que los Titulares no manifieste su oposición se entenderá que otorgan su consentimiento a <strong>VPD</strong>. </p>
			<p>Es responsabilidad del Titular de los Datos Personales, el garantizar que los datos que facilite personal o directamente a <strong>VPD</strong> sean veraces y completos, así como de notificar a <strong>VPD</strong> cualquier modificación a los mismos para dar cumplimiento a la obligación de mantener la información actualizada.</p>
			<h3>3.- FINALIDADES PARA LAS QUE SE RECABAN LOS DATOS PERSONALES</h3>
			<p>La información de Datos Personales, que es recolectada por <strong>VPD</strong> del Titular tendrá el uso que se describe a continuación: <strong>i)</strong> para el cumplimiento de los contratos que celebre <strong>VPD</strong> con el Titular (en adelante los Contratos), <strong>ii)</strong> para la identificación del Titular, <strong>iii)</strong> para la administración de los Contratos, <strong>iv)</strong> para la actualización de datos del Titular, <strong>v)</strong> proporcionar seguridad a las instalaciones de <strong>VPD</strong> y a los Titulares que ingresen a éstas últimas, finalidades que son necesarias para cumplir las obligaciones derivadas de la relación jurídica que tenga <strong>VPD</strong> con el Titular.</p>
			<p>En relación a los Datos Personales de aquellos Titulares que en el pasado otorgaron sus datos a <strong>VPD</strong> y que actualmente ya no tienen una relación jurídica con éste último, se les informa a dichos Titulares que <strong>VPD</strong> únicamente conserva sus Datos Personales de conformidad a lo dispuesto por el artículo 25 de la Ley, es decir, durante el periodo de bloqueo<span class="sprRmn">1</span> establecido en dicho ordenamiento legal, por lo que, una vez transcurrido dicho periodo de bloqueo sus Datos Personales serán suprimidos.</p>
			<h3>4.- TEMPORALIDAD, REMISIONES Y TRANSFERENCIAS</h3>
			<p>La temporalidad del manejo de los Datos Personales del Titular, dependerá de la relación jurídica que se tenga celebrada con <strong>VPD</strong>, así como de las obligaciones exigidas por la legislación vigente las autoridades competentes y las políticas internas de <strong>VPD</strong>, sin embargo, en relación a los Datos Personales correspondientes a la imagen del Titular que es captada por las cámaras de videovigilancia, dicha información es conservada por <strong>VPD</strong> únicamente por un plazo de 30 (treinta) a 60 (sesenta) días hábiles posteriores a la fecha en la que se obtiene. </p>
			<p>La información que sea entregada a <strong>VPD</strong>, será  resguardada, conservada y protegida, por éste último de acuerdo a lo dispuesto por la legislación vigente y las políticas internas de <strong>VPD</strong> para efecto de mantener la confidencialidad de dicha información. </p>
			<p>De acuerdo a lo dispuesto por la Ley, <strong>VPD</strong> dará acceso a los Datos Personales del Titular (a través de remisiones) a aquellas personas que tengan el carácter de Encargados<span class="sprRmn">2</span> como pueden ser prestadores de servicios, socios de negocios o terceros, que tengan una relación jurídica con <strong>VPD</strong>, que derivado de dicha relación jurídica necesiten conocer la información y asuman el compromiso de mantenerla bajo un estricto orden de confidencialidad y seguridad reconociendo además conocer los términos y condiciones del presente Aviso de Privacidad y comprometiéndose a dar cumplimiento a los mismos.</p>
			<p>Por otra parte, <strong>VPD</strong> transmite los Datos Personales de los Titulares a las empresas filiales y/o subsidiarias de <strong>VPD </strong>con la finalidad de cumplir con las relaciones jurídicas que existen entre dichas empresas transferencias que no requieren del consentimiento del Titular de acuerdo a lo dispuesto en el artículo 37 de la LFPDP.</p>
			<p>En caso de que los Datos Personales resguardados sean requeridos por una autoridad de cualquier índole o deban ser entregados a ésta última de acuerdo a la legislación vigente, estos datos se pondrán a su disposición dentro del estricto cumplimiento a la Ley, transferencia que no requiere del consentimiento del Titular de acuerdo a lo dispuesto en el artículo 37 de dicho ordenamiento legal.</p>
			<h3>5.- DERECHOS DE ACCESO, RECTIFICACIÓN, CANCELACIÓN, OPOSICIÓN, REVOCACIÓN Y LIMITACIÓN DE LOS DATOS PERSONALES.</h3>
			<p>Los Titulares de la información tendrán derecho a solicitar el acceso, rectificación, revocación, cancelación u oposición así como limitar el uso o divulgación de sus datos, mediante:</p>
			<p>a.- Solicitud escrita dirigida a la Vicepresidencia Jurídica y de Asuntos Corporativos de Vinos Pedro Domecq S.A. de C.V., al siguiente domicilio: Paseo de los Tamarindos 100, piso 3, Colonia Bosques de las Lomas, Delegación Cuajimalpa, México Distrito Federal, Código Postal 05120, de las 10:00 a las 17:00 horas, en días hábiles, o</p>
			<p>b.- Solicitud formulada al correo electrónico <a href="mailto:mxdatospersonales@pernod-ricard.com" class="lnk">mxdatospersonales@pernod-ricard.com</a></p>
			<p><strong>VPD</strong>, dará respuesta a las solicitudes del Titular de la información, siempre y cuando no se actualice alguna de las excepciones contenidas en la Ley, y el solicitante cumpla con lo dispuesto en el artículo 29 de dicho ordenamiento legal que establece los requisitos que debe contener las solicitudes presentadas por los Titulares.</p>
			<p>Para que <strong>VPD</strong> de trámite a la solicitud de un Titular referente al acceso, rectificación, revocación, cancelación, oposición y/o limitación del uso o divulgación de sus datos, éste último deberá adjuntar a su solicitud la siguiente información y documentación:</p>
			<ul class="lwr-Ltn">
				<li>Nombre del Titular y domicilio u otro medio para que <strong>VPD</strong> le comunique la respuesta a su solicitud.</li>
				<li>Los documentos con los que acredite su identidad o su personalidad en caso de la representación legal del Titular (identificación oficial del titular o del representante legal y poder de éste último). </li>
				<li>La descripción clara y precisa de los Datos Personales respecto de los que se busca ejercer el derecho de acceso, rectificación, revocación, cancelación, oposición, limitación del uso o divulgación, así como cualquier otro dato o documento que pueda facilitar la localización de los Datos Personales. </li>
			</ul>
			<p><strong>VPD</strong><strong> </strong>dará respuesta a la solicitud de un Titular referente al acceso, rectificación, revocación, cancelación, oposición y/o limitación del uso o divulgación de sus datos dentro de los plazos establecidos en la Ley, es decir, dentro de los veinte (20) días siguientes contados a partir de que reciba la solicitud del Titular y en caso de que la solicitud sea procedente la misma se implementará dentro de los 15 (quince) días siguientes a que se le comunique al Titular la respuesta, plazo que podrá ser ampliado por <strong>VPD</strong> de acuerdo a lo dispuesto por el artículo 32 de la Ley. </p>
			<p>La obligación de acceso a la información se dará por cumplida por <strong>VPD</strong> cuando, en caso de que sea solicitado por el Titular, se ponga a disposición de éste último sus Datos Personales en copia simple en el domicilio de <strong>VPD</strong> durante el plazo de 15 (quince) días hábiles siguientes a que se le comunique al Titular la respuesta a su solicitud o bien a través de alguna de las formas establecidas en el artículo 33 de la Ley, mismas que en la respuesta a su solicitud se le notificarán al Titular.</p>
			<h3>6.- MODIFICACIONES AL AVISO DE PRIVACIDAD</h3>
			<p>En el supuesto, de que <strong>VPD</strong>, requiera usar sus Datos Personales con fines distintos a los pactados o convenidos al tenor de la relación jurídica que se tiene con el Titular y en el presente Aviso de Privacidad o bien requiera del Titular Datos Personales distintos a los señalados en el presente Aviso de Privacidad o pretenda realizar transferencias de los Datos Personales distintas a las señaladas en el presente Aviso de Privacidad, se notificará al Titular en forma escrita, telefónica, electrónica, o por cualquier medio óptico, sonoro, visual u otro que la tecnología permita ahora o en lo futuro explicando los nuevos usos que pretenda darle a dicha información a fin de obtener su consentimiento en términos de la Ley. Con el presente Aviso de Privacidad, los Titulares de la información quedan debidamente informados de los datos que se recabaron de ellos y con qué fines así como del hecho de que el Aviso de Privacidad podrá en todo momento ser consultado en la página de internet de <strong>VPD</strong> <a href="http://www.pernod-ricard-mexico.com" class="lnk">www.pernod-ricard-mexico.com</a>. </p>
			<p><strong>VPD</strong>, se reserva el derecho a modificar el presente Aviso de Privacidad para adaptarlo a novedades legislativas o jurisprudenciales así como a prácticas comerciales. En dichos supuestos, se anunciará en la página de internet <a href="http://www.pernod-ricard-mexico.com" class="lnk">www.pernod-ricard-mexico.com</a> los cambios de referencia. </p>
			<p>El presente Aviso de Privacidad, así como el manejo en general de la Ley que haga <strong>VPD</strong>, se rige por la legislación vigente y aplicable en los Estados Unidos Mexicanos, cualquier controversia que se suscite con motivo de su aplicación deberá ventilarse ante el Instituto Federal de Acceso a la Información y Protección de Datos (IFAI) o ante los Órganos Jurisdiccionales competentes en la Ciudad de México, Distrito Federal.</p>
			<p>Última actualización 1 de octubre de 2013.</p>
			<p>Consiento y autorizo que mis Datos Personales sean tratados conforme los términos y condiciones del presente Aviso de Privacidad.</p>
			<p>_______________________________ (Nombre y firma)</p>
			<hr>
			<small><span class="sprRmn">1</span> Artículo 3 Fracción  III de la Ley  Federal de Protección de Datos Personales en Posesión de los Particulares  establece que el Bloqueo es: La identificación y conservación de datos  personales una vez cumplida la finalidad para   la cual fueron recabados, con el único propósito de determinar posibles  responsabilidades en  relación con su  tratamiento, hasta el plazo de prescripción legal o contractual de éstas.  Durante  dicho periodo, los datos  personales no podrán ser objeto de tratamiento y transcurrido éste, se  procederá a su cancelación en la base de  datos que corresponde. </small><br>
			<small><span class="sprRmn">2</span>El  artículo 3 de la Ley Federal de Protección de Datos Personales en Posesión de  los Particulares establece que el Encargado es la persona física o jurídica que  sola o conjuntamente con otras trate datos personales por cuenta del  Responsable. </small>
		</div>
		<div id="Rep_Leg_INVIDO_YYN_130902" class="pUpAP-Frmt">
			<h2>AVISO DE PRIVACIDAD</h2>
			<p>En cumplimiento a lo previsto en la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (en lo sucesivo &quot;la Ley&quot;), nos permitimos informarle lo siguiente:</p>
			<h3>1.- RESPONSABLE DE LOS DATOS PERSONALES</h3>
			<p>Industrias Vinícolas Pedro Domecq S.A. de C.V., (en lo sucesivo la &ldquo;Sociedad&rdquo;), señalando para efectos del presente Aviso de Privacidad el domicilio ubicado en Paseo de los Tamarindos 100, piso 3, Colonia Bosques de las Lomas, Delegación Cuajimalpa, México Distrito Federal, Código Postal 05120, será el responsable de los datos personales que le sean proporcionados de las personas físicas a quienes correspondan los mismos y que sean apoderados o representantes legales de una persona que pretenda tener o que en su caso tenga una relación con la Sociedad (en lo sucesivo el &ldquo;Titular&rdquo; o los &ldquo;Titulares&rdquo;, indistintamente).</p>
			<h3>2.- DATOS PERSONALES QUE SE SOLICITAN DEL TITULAR</h3>
			<p>Para las finalidades señaladas en el presente Aviso de Privacidad, la Sociedad podrá recabar los Datos Personales de los Titulares como son: nombre completo (identificación oficial así como la imagen del Titular al ingresa a las instalaciones de la Sociedad a través de las cámaras de videovigilancia y seguridad), estado civil, domicilio, nacionalidad, Registro Federal de Contribuyentes (RFC), y ocupación o actividad profesional (en adelante y en su conjunto los Datos Personales).</p>
			<p>Los Datos Personales de los Titulares se podrán recabar de las siguientes formas: <strong>i)</strong> cuando los Titulares los proporcione personal o directamente,<strong> ii)</strong> cuando la Sociedad los obtenga de forma indirecta y <strong>iii)</strong> cuando se obtengan por la Sociedad a través de las fuentes permitidas por la legislación.</p>
			<p>En términos de lo dispuesto por el artículo 14 del Reglamento de la Ley cuando la Sociedad no haga del conocimiento de los Titulares el presente Aviso de Privacidad de manera directa o personal sino de forma indirecta, los Titulares cuentan con un plazo de 5 (cinco) días hábiles a partir de que les fue puesto a disposición el Aviso de Privacidad para que de ser el caso manifiesten su oposición al tratamiento de sus Datos Personales que pretendan ser utilizados por la Sociedad para finalidades no necesarias para cumplir una relación jurídica con éste último, oposición que deberán manifestar de acuerdo a lo dispuesto en la sección cinco (5) del presente Aviso de Privacidad, ya que, en caso de que los Titulares no manifieste su oposición se entenderá que otorgan su consentimiento a la Sociedad.</p>
			<p>Es responsabilidad de los Titulares de los Datos Personales, el garantizar que los datos que faciliten personal o directamente a la Sociedad sean veraces y completos, así como de notificar a la Sociedad cualquier modificación a los mismos para dar cumplimiento a la obligación de mantener la información actualizada.</p>
			<h3>3.- FINALIDADES PARA LAS QUE SE RECABAN LOS DATOS PERSONALES</h3>
			<p>La información de Datos Personales, que es recolectada por la Sociedad de los Titulares tendrá el uso que se describe a continuación: <strong>i)</strong> para la identificación de los Titulares,<strong> ii) </strong>para verificar las facultades que le hayan sido otorgadas a los Titulares por su poderdante e incluir sus Datos Personales en los documentos que deban ser suscritos con éste último, <strong>iii)</strong> para la actualización de los Datos Personales de los Titulares y <strong>iv)</strong> proporcionar seguridad a las instalaciones de la Sociedad y a los Titulares que ingresen a éstas últimas, finalidades que son necesarias para cumplir las obligaciones derivadas de la relación jurídica que tenga la Sociedad con los Titulares.</p>
			<p>En relación a los Datos Personales de aquellos Titulares que son o fueron apoderados o representantes legales de personas que tenían una relación con la Sociedad y que actualmente ya no la tienen, así como de personas que pretendan o pretendían tener una relación con la Sociedad y que dicha relación no sea perfeccionada y/o de los Titulares que eran apoderados o representantes legales de una persona que tenga una relación con la Sociedad así como de personas que pretendan o pretendían tener una relación con la Sociedad y que dicha relación no sea perfeccionada y dejen de ser o hayan dejado de ser apoderados o representantes legales de dicha persona, se les informa que la Sociedad únicamente conserva sus Datos Personales de conformidad a lo dispuesto por el artículo 25 de la Ley, es decir, durante el periodo de bloqueo<span class="sprRmn">1</span> establecido en dicho ordenamiento legal, por lo que, una vez transcurrido dicho periodo de bloqueo sus Datos Personales serán suprimidos. </p>
			<h3>4.- TEMPORALIDAD, REMISIONES Y TRANSFERENCIAS</h3>
			<p>La temporalidad del manejo de los Datos Personales de los Titulares, dependerá de la relación que se tengan con la Sociedad, así como de las obligaciones exigidas por la legislación vigente y las autoridades competentes, sin embargo, en relación a los Datos Personales correspondientes a la imagen de los Titulares que es captada por las cámaras de videovigilancia, dicha información es conservada por la Sociedad únicamente por un plazo de 30 (treinta) a 60 (sesenta) días hábiles posteriores a la fecha en la que se obtiene y una vez transcurrido dicho plazo es suprimida. </p>
			<p>La información que sea entregada a la Sociedad, será  resguardada, conservada y protegida, por ésta última de acuerdo a lo dispuesto por la legislación vigente para efecto de mantener la confidencialidad de dicha información.</p>
			<p>De acuerdo a lo dispuesto por la Ley, la Sociedad dará acceso a los Datos Personales de los Titulares (a través de remisiones) a aquellas personas que tengan el carácter de Encargados<span class="sprRmn">1</span> como pueden ser terceros, proveedores de servicios, o socios de negocios de la Sociedad, que tengan una relación jurídica con ésta última, que derivado de dicha relación jurídica necesiten conocer la información y asuman el compromiso de mantenerla bajo un estricto orden de confidencialidad y seguridad reconociendo además conocer los términos y condiciones del presente Aviso de Privacidad y comprometiéndose a dar cumplimiento a los mismos.</p>
			<p>Por otra parte, los Datos Personales de los Titulares son transferidos por la Sociedad a las empresas filiales y subsidiarias nacionales o extranjeras de la Sociedad con la finalidad de de cumplir con las relaciones jurídicas que existen entre dichas empresas, transferencia que no requiere del consentimiento del Titular de acuerdo a lo dispuesto en el artículo 37 de la Ley.</p>
			<p>Asimismo, en caso de que los Datos Personales resguardados sean requeridos por una autoridad de cualquier índole o deban ser entregados a ésta última de acuerdo a la legislación vigente, estos datos se pondrán a su disposición dentro del estricto cumplimiento a la Ley, transferencias que no requieren del consentimiento de los Titulares de acuerdo a lo dispuesto en el artículo 37 de dicho ordenamiento legal.</p>
			<h3>5.- DERECHOS DE ACCESO, RECTIFICACIÓN, CANCELACIÓN, OPOSICIÓN, REVOCACIÓN Y LIMITACIÓN DE LOS DATOS PERSONALES.</h3>
			<p>Los Titulares de la información tendrán derecho a solicitar el acceso, rectificación, revocación, cancelación u oposición así como limitar el uso o divulgación de sus datos, mediante:</p>
			<p>1.- Solicitud escrita dirigida genéricamente a la Vicepresidencia Jurídica y de Asuntos Corporativos de Industrias Vinícolas Pedro Domecq S.A. de C.V., al siguiente domicilio: Paseo de los Tamarindos 100, piso 3, Colonia Bosques de las Lomas, Delegación Cuajimalpa, México Distrito Federal, Código Postal 05120, de las 10:00 a las 17:00 horas, en días hábiles, o </p>
			<p>2.- Solicitud formulada al correo electrónico <a href="mailto:mxdatospersonales@pernod-ricard.com" class="lnk">mxdatospersonales@pernod-ricard.com</a></p>
			<p>La Sociedad dará respuesta a las solicitudes de los Titulares de la información, siempre y cuando no se actualice alguna de las excepciones contenidas en la Ley, y el solicitante cumpla con lo dispuesto en el artículo 29 de dicho ordenamiento legal que establece los requisitos que debe contener las solicitudes presentadas por los Titulares.</p>
			<p>Para que la Sociedad de trámite a la solicitud de un Titular referente al acceso, rectificación, revocación, cancelación, oposición y/o limitación del uso o divulgación de sus datos, éste último deberá adjuntar a su solicitud la siguiente información y documentación:</p>
			<ul class="lwr-Ltn">
				<li>Nombre del Titular y domicilio u otro medio para que la Sociedad le comunique la respuesta a su solicitud.</li>
				<li>Los documentos con los que acredite su identidad o su personalidad en caso de la representación legal del Titular (identificación oficial del titular o del representante legal y poder de éste último).</li>
				<li>La descripción clara y precisa de los Datos Personales respecto de los que se busca ejercer el derecho de acceso, rectificación, revocación, cancelación, oposición, limitación del uso o divulgación, así como cualquier otro dato o documento que pueda facilitar la localización de los Datos Personales. </li>
			</ul>
			<p>La Sociedad dará respuesta a la solicitud de un Titular referente al acceso, rectificación, revocación, cancelación, oposición y/o limitación del uso o divulgación de sus datos dentro de los plazos establecidos en la Ley, es decir, dentro de los veinte (20) días siguientes contados a partir de que reciba la solicitud del Titular y en caso de que la solicitud sea procedente la misma se implementará dentro de los 15 (quince) días siguientes a que se le comunique al Titular la respuesta, plazos que podrán ser ampliados por la Sociedad de acuerdo a lo dispuesto por el artículo 32 de la Ley.</p>
			<p>La obligación de acceso a la información se dará por cumplida por la Sociedad cuando, en caso de que sea solicitado por el Titular, se ponga a disposición de éste último copias simples de sus Datos Personales en el domicilio de la Sociedad durante el plazo de 15 (quince) días hábiles siguientes a que se le comunique al Titular la respuesta a su solicitud o bien a través de alguna de las formas establecidas en el artículo 33 de la Ley, mismas que en la respuesta a su solicitud se le notificarán al Titular.</p>
			<h3>6.- MODIFICACIONES AL AVISO DE PRIVACIDAD</h3>
			<p>En el supuesto, de que la Sociedad, requiera usar sus Datos Personales con fines distintos a los pactados o convenidos al tenor de la relación que se tiene con los Titulares y en el presente Aviso de Privacidad o bien requiera de los Titulares Datos Personales distintos a los señalados en el presente Aviso de Privacidad o pretenda realizar transferencias de los Datos Personales distintas a las señaladas en el presente Aviso, se notificará a los Titulares en forma escrita, telefónica, electrónica, o por cualquier medio óptico, sonoro, visual u otro que la tecnología permita ahora o en lo futuro explicando los nuevos usos que pretenda darle a dicha información a fin de obtener su autorización. Con el presente Aviso de Privacidad, los Titulares de la información quedan debidamente informados de los datos que se recabaron de ellos y con qué fines así como del hecho de que el Aviso de Privacidad podrá en todo momento ser consultado en la página de internet de la Sociedad <a href="http://www.pernod-ricard-mexico.com" class="lnk">www.pernod-ricard-mexico.com</a>   </p>
			<p>La Sociedad se reserva el derecho a modificar el presente Aviso de Privacidad para adaptarlo a novedades legislativas o jurisprudenciales así como a criterios de la autoridad. En dichos supuestos, se anunciará en la página de internet <a href="http://www.pernod-ricard-mexico.com" class="lnk">www.pernod-ricard-mexico.com</a> los cambios de referencia. </p>
			<p>El presente Aviso de Privacidad, así como el manejo en general de la Ley que haga la Sociedad, se rige por la legislación vigente y aplicable en los Estados Unidos Mexicanos, cualquier controversia que se suscite con motivo de su aplicación deberá ventilarse ante el Instituto Federal de Acceso a la Información y Protección de Datos (IFAI) o ante los Órganos Jurisdiccionales competentes en la Ciudad de México, Distrito Federal.</p>
			<p>Última actualización 12 de agosto de 2013.</p>
			<p>Consiento y autorizo que mis Datos Personales sean tratados conforme los términos y condiciones del presente Aviso de Privacidad.</p>
			<p>_______________________________ (Nombre y firma)</p>
			<hr>
			<small><span class="sprRmn">1</span> Artículo 3 Fracción  III  de la Ley Federal de Protección de Datos Personales en Posesión de los  Particulares establece que el  Bloqueo es: La identificación y conservación de  datos personales una vez cumplida la finalidad para  la cual fueron  recabados, con el único propósito de determinar posibles responsabilidades en  relación  con su tratamiento, hasta el plazo de prescripción legal o contractual de  éstas. Durante  dicho  periodo, los datos personales no podrán ser objeto de tratamiento y  transcurrido éste, se  procederá a su cancelación en la base  de datos que corresponde. </small><br>
			<small><span class="sprRmn">2</span>El  artículo 3  Fracción IX de la Ley Federal  de Protección de Datos Personales en Posesión de los Particulares establece que  el Encargado es: La persona física o jurídica que sola o conjuntamente con  otras trate datos personales por cuenta del Responsable. </small>
		</div>
		<?php include('libs/footer'); ?>
		<script src="/js/jquery.fancybox.min.js"></script>
		<script src="/js/query.min.js"></script>
		<script type="text/javascript">
			jQuery(function($) {
				$('.knwAP').fancybox();
			});
		</script>
	</body>
</html>